# ==========================================
# Application
# ==========================================
spring.application.name=erp

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:false}

erp.super.user.email=${ERP_SUPER_USER_EMAIL}
erp.super.user.password=${ERP_SUPER_USER_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/api/v1}