# ==========================================
# Application
# ==========================================
spring.application.name=erp

# ==========================================
# Database
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ==========================================
# JPA
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# Flyway
# ==========================================
spring.flyway.enabled=false

# ==========================================
# Server
# ==========================================
server.port=${PORT:8080}
server.servlet.context-path=/api/v1

# ==========================================
# Logging
# ==========================================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================================
# ERP Super Admin
# ==========================================
erp.super.user.email=${SUPER_ADMIN_EMAIL}
erp.super.user.password=${SUPER_ADMIN_PASSWORD}

# ==========================================
# JWT
# ==========================================
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}